#!/bin/sh

VERSION=/etc/config/device.version

cat << EOF
Content-type: text/html

<html>
    <body>
        <h1>Update</h1>
        Current version: $(cat $VERSION) <br />
        <form name="query" action="/cgi-bin/do_update" method="get">
            File name:
            <br />
            <input type="text" name="file"/>
            <br />
            IP:
            <br />
            <input type="text" name="ip"/>
            <input type="checkbox" name="useip"/>
            <br />
            <br />
            <input type="submit" value="Submit"/>
        </form>
    </body>
</html>

EOF
