#!/bin/sh

APP=AirSniffer
UPDATER=cfg_updater
CONFIG_FILE=/etc/config/device.conf

eval $(echo "$QUERY_STRING"|awk -F'&' '{for(i=1;i<=NF;i++){print $i}}')

if [ "$useip" == "on" ]; then
    HOST=$ip
else
    HOST=$REMOTE_ADDR
fi

cd /tmp

OUT=$(tftp -g -r $file $HOST 2>&1)

if [ "$?" == "0" ]; then
    #Success
    killall $APP
    
    tr -d '\015' <$file >new.conf
    rm $file
    
    source new.conf
    
    if [ -n "$mac" ]; then
        cat /dev/mtd2 > hexd
        
        old_IFS=$IFS
        IFS=':'
        array=$mac
        fs=""
        for i in $array; do
            fs="$fs\x$i"
        done
        IFS=$old_IFS
        
        printf "$fs" | dd of=hexd bs=1 seek=4 count=6 conv=notrunc
        
        mtd erase factory
        mtd write hexd factory
        rm hexd
    fi
    
    if [ "$update" == "on" ]; then
        OUT=$("$OUT@@@@@$UPDATER new.conf $CONFIG_FILE 2>&1")
    else
        cat new.conf > $CONFIG_FILE
    fi
    
    rm new.conf
    
    (sleep 10; Welcome; reboot)&
    
    cat << EOF
    Content-type: text/html

    <html>
        <head>
            <title>Success</title>
        </head>
        <body>
            <h2>Device config updated</h2>
            <p>reboot in 10 seconds</p>
        </body>
    </html>
EOF
    
else
    #Failed
    cat << EOF
    Content-type: text/html

    <html>
        <head>
            <title>Failed</title>
        </head>
        <body>
            <h2>Update Failed</h2>
            <p>$OUT</p>
        </body>
    </html>
EOF
fi
